/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jonmarx_discord_RichTextManager */

#ifndef _Included_com_jonmarx_discord_RichTextManager
#define _Included_com_jonmarx_discord_RichTextManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jonmarx_discord_RichTextManager
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jonmarx_discord_RichTextManager_init
  (JNIEnv *, jobject);

/*
 * Class:     com_jonmarx_discord_RichTextManager
 * Method:    pushRichText
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jonmarx_discord_RichTextManager_pushRichText
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jonmarx_discord_RichTextManager
 * Method:    tick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jonmarx_discord_RichTextManager_tick
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
