/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jonmarx_discord_RichTextManager_RichTextWrapper */

#ifndef _Included_com_jonmarx_discord_RichTextManager_RichTextWrapper
#define _Included_com_jonmarx_discord_RichTextManager_RichTextWrapper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
